version: '3.8'

services:
  fastapi:
    build: ./fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app

  streamlit:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    volumes:
      - ./streamlit_app:/app
